### ISSUE TITLE
prepare reana.yaml

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-demo-bsm-search#2]
"Reanify" BSM search example.

**Comment by tiborsimko** [comment]
Here is the work-in-progress branch:

- https://github.com/tiborsimko/reana-demo-bsm-search/commits/2-reanification-new

While the workflow runs fine locally with Yadage, I have met problems running the workflow through REANA.  This is apparently due to `par_mounts` with absolute directory mounting instructions such as  here:

```yaml
select_mc:
  process:
    process_type: interpolated-script-cmd
    interpreter: bash
    script: |
      source /usr/local/bin/thisroot.sh
      variations=$(cat /parmounts/variations|sed 's|"||g'|paste -sd , -)
      python /code/select.py {inputfile} {outputfile} {region} $variations
  environment:
    environment_type: docker-encapsulated
    image: reanahub/reana-demo-bsm-search
    par_mounts:
      - mountpath: /parmounts/variations
        jqscript: .variations[]
  publisher:
    publisher_type: 'frompar-pub'
    outputmap:
      outputfile: 'outputfile'
```

Here are the logs from one failed job:

```console
$ kubectl logs 89774ec5-a40b-4c5f-9bd4-7edd5e925399-pwgfm
cat: /parmounts/inputs: No such file or directory
Usage: hadd [-f[0-9]] [-k] [-T] [-O] [-n maxopenedfiles] [-v verbosity] targetfile source1 [source2 source3 ...]
This program will add histograms from a list of root files and write them
...
```

@lukasheinrich Is it possible to refactor the example so that it would not use `/parmounts` absolute mount paths?

@diegodelemos @dinosk Have you tried to run some Yadage workflows that were using the `mountpath` feature on REANA in the past?
